name: Update Repo Stats

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Update stats
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: ${{ github.repository_owner }}
        run: |
          python3 - <<EOF
          import json
          import requests
          import os

          headers = {
              "Authorization": f"token {os.getenv('GH_TOKEN')}",
              "Accept": "application/vnd.github.v3+json"
          }

          user = os.getenv('GH_USER')
          repos_url = f"https://api.github.com/users/{user}/repos?per_page=100&type=public"
          repos = requests.get(repos_url, headers=headers).json()

          projects = []
          for repo in repos:
              name = repo['name']
              stars = repo['stargazers_count']

              clones_url = f"https://api.github.com/repos/{user}/{name}/traffic/clones"
              visitors_url = f"https://api.github.com/repos/{user}/{name}/traffic/views"

              clones = requests.get(clones_url, headers=headers).json()
              visitors = requests.get(visitors_url, headers=headers).json()

              project_data = {
                  "name": name,
                  "stars": stars,
                  "clones_last_14_days": clones.get('count', 0),
                  "clones_unique": clones.get('uniques', 0),
                  "visitors_last_14_days": visitors.get('count', 0),
                  "visitors_unique": visitors.get('uniques', 0)
              }

              projects.append(project_data)

          with open('projects.json', 'w') as f:
              json.dump(projects, f, indent=2)

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add projects.json
          git commit -m "Update project stars and traffic"
          git push
